---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
