# spell-checker: disable
---
version: "2"
run:
  concurrency: 6
output:
  path-prefix: v2
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # NOTE: Too noisy in this repo
    # - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/memes
            - github.com/go-logr
            - github.com/gomodule/redigo/redis
            - github.com/google/uuid
            - github.com/grpc-ecosystem/grpc-gateway/v2/runtime
            - github.com/mitchellh/go-homedir
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/rs/zerolog
            - go.opentelemetry.io/contrib/detectors/gcp
            - go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
            - go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
            - go.opentelemetry.io/contrib/instrumentation/runtime
            - go.opentelemetry.io/otel
            - google.golang.org/grpc
            - golang.org/x/net/context
            - golang.org/x/sync/errgroup
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/memes
            - github.com/alicebob/miniredis
            - github.com/go-logr
            - github.com/google/uuid
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        # gRPC/XDS credentials are returned as interfaces by those libraries
        - google.golang.org\/grpc\/credentials.TransportCredentials
    nakedret:
      max-func-lines: 1
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    tagliatelle:
      case:
        rules:
          avro: camel
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/generated
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/generated
      - third_party$
      - builtin$
      - examples$
