# spell-checker: disable
---
run:
  concurrency: 6
  timeout: 5m
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude-dirs:
    - pkg/generated
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    # NOTE: Too noisy in this repo
    # - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/memes
          - github.com/go-logr
          - github.com/gomodule/redigo/redis
          - github.com/google/uuid
          - github.com/grpc-ecosystem/grpc-gateway/v2/runtime
          - github.com/mitchellh/go-homedir
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/rs/zerolog
      test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/memes
          - github.com/alicebob/miniredis
          - github.com/go-logr
          - github.com/google/uuid
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      # gRPC/XDS credentials are returned as interfaces by those libraries
      - google.golang.org\/grpc\/credentials.TransportCredentials
  nakedret:
    max-func-lines: 1
  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: true
    require-specific: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: camel
        mapstructure: kebab
output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: "v2"
  sort-results: true
