# use goreleaser for builds and containers
# spell-checker: ignore goreleaser yamllint incpatch goarch opencontainers
---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - memes/pi:latest
      - memes/pi:{{ .Tag }}
      - memes/pi:{{ .Major }}
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      # yamllint disable rule:line-length
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/memes/pi/tree/{{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://github.com/memes/pi/tree/{{ .FullCommit }}/README.md"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.label-schema.vcs-url=https://github.com/memes/pi/tree/{{ .FullCommit }}"
      - "--label=org.label-schema.usage=https://github.com/memes/pi/tree/{{ .FullCommit }}/README.md"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
      # yamllint enable rule:line-length
release:
  draft: false
  prerelease: auto
