# use goreleaser for v2 builds and containers
# spell-checker: disable
---
version: 2
project_name: pi
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}-{{ .Commit }}
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goarm: 6
    main: ./cmd/pi/
    mod_timestamp: '{{ .CommitTimestamp }}'
gomod:
  proxy: true
archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
source:
  enabled: true
  name_template: '{{ .ProjectName }}.src'
checksum:
  name_template: 'checksums.txt'
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source
signs:
  - artifacts: checksum
    cmd: cosign
    signature: '${artifact}.sigstore.json'
    args:
      - sign-blob
      - '--bundle=${signature}'
      - '${artifact}'
      - '--yes'
    output: true
snapshot:
  version_template: '{{ incpatch .Tag }}-next'
changelog:
  disable: true
dockers_v2:
  - images:
      - 'memes/{{ .ProjectName }}'
      - 'ghcr.io/memes/{{ .ProjectName }}'
    tags:
      - latest
      - '{{ .Tag }}'
      - '{{ .Major }}'
    dockerfile: ../Dockerfile
    labels:
      maintainer: 'Matthew Emes <memes@matthewemes.com>'
      org.opencontainers.image.title: '{{ .ProjectName }}'
      org.opencontainers.image.authors: 'memes@matthewemes.com'
      org.opencontainers.image.description: 'Return the decimal digit of pi at an index'
      org.opencontainers.image.licenses: 'MIT'
      org.opencontainers.image.created: '{{ .Date }}'
      org.opencontainers.image.source: '{{ .GitURL }}'
      org.opencontainers.image.documentation: '{{ .GitURL }}/tree/{{ .FullCommit }}/README.md'
      org.opencontainers.image.version: '{{ .Version }}'
      org.opencontainers.image.revision: '{{ .FullCommit }}'
      org.opencontainers.image.url: '{{ .GitURL }}/tree/{{ .FullCommit }}/README.md'
    annotations:
      'index:org.opencontainers.image.description': Return the decimal digit of pi at an index
docker_signs:
  - cmd: cosign
    output: true
    args:
      - sign
      - '${artifact}'
      - '--yes'
release:
  draft: false
  prerelease: auto
milestones:
  - close: true
    fail_on_error: false
    name_template: '{{ .Tag }}'
