# Configure otel-collector under podman
---
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: :8889

  logging:

  jaeger:
    endpoint: :14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions:
    - pprof
    - zpages
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - jaeger
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - prometheus
