# prometheus in podman
---
scrape_configs:
  - job_name: otel-collector
    scrape_interval: 10s
    static_configs:
      - targets:
          - :8889
      - targets:
          - :8888
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - :9090
