# spell-checker: disable
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v2*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: v2/go.mod
          cache: true
          cache-dependency-path: v2/go.sum
      - name: Install cosign
        if: ${{ success() }}
        uses: sigstore/cosign-installer@v3.5.0
      - name: Install syft
        if: ${{ success() }}
        uses: anchore/sbom-action/download-syft@v0.17.0
      - id: docker-login
        name: Login to Docker hub
        if: ${{ success() }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - id: ghcr-login
        name: Login to GitHub Container Registry
        if: ${{ success() }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Go Report update
        if: ${{ success() }}
        uses: fjogeleit/http-request-action@v1.16.1
        with:
          url: 'https://goreportcard.com/checks'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: 'repo=github.com/${{ github.repository }}/v2'
          preventFailureOnNoResponse: 'true'
